### ISSUE TITLE
Fix double free or corruption after terminating AFL-rb

### ISSUE THREAD

**Issue by carolemieux** [carolemieux/afl-rb#1]
Sometimes during the temination of a 24 hour run, afl-rb fails with double-free or corruption. Need to reproduce + investigate.

**Comment by dkasak** [comment]
I'm not sure whether it's the same problem, but I've had FairFuzz's afl-fuzz crash due freeing an invalid pointer shortly after the session started:

    *** Error in `/home/dkasak/code/projects/afl-rb/afl-fuzz': free(): invalid pointer: 0x000055d74dab4290 ***

**Comment by carolemieux** [comment]
can you share what binary you were fuzzing?

**Comment by dkasak** [comment]
Unfortunately no since it's a proprietary binary which I can't distribute. However, I think I may have fixed the bug at least partially in #6. I've been running an instance for just over 4 hours now with no crashes (and no memory errors which would usually get caught by ASAN). It usually crashed much sooner but I'll leave it running longer and report back.

**Comment by dkasak** [comment]
I've been running the instance for over 24 hours without seeing the double free or any other ASAN-detectable memory error before ASAN finally failed because it was unable to allocate enough memory. I think that may well be something spurious related to the use of ASAN itself and my workload at that moment instead of afl-rb genuinely using too much memory, though.

**Comment by carolemieux** [comment]
I am tentatively closing this issue. I just fixed a leak (see issue #9) but that is probably not the cause of the use of too much memory since the amount of memory not de-alloc'd was proportional to the number of provided and did not grow over time.
