### ISSUE TITLE
Full blacklist

### ISSUE THREAD

**Issue by dkasak** [carolemieux/afl-rb#7]
I managed to stumble onto `Too many things on the blacklist` while fuzzing. I can see from the comment in the code that you're already aware of it, but I wasn't sure whether you've ever managed to hit it in practice, so just letting you know.

**Comment by carolemieux** [comment]
Had not seen this in practice. Fixed in 88a558e.

**Comment by carolemieux** [comment]
p.s. I've added a logging statement to state that the branch has been put on the blacklist so that we could see this. I'd be interested in knowing what min-branch-fuzzing.log looks like for branches on your blacklist for this benchmark. Notably, whether any of the havoc mutations hit the input of interest. (to know whether Issue #8 would do more harm than good)
